backend:
  name: gitlab
  repo: <USER>/<REPO>
  auth_type: implicit
  app_id: <GITLAB APP ID>

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "data/home.yml"
        fields:
          - {label: Title, name: title, widget: string}